In [1]:
import pandas as pd
import numpy as np
import csv
import math
import os,sys
from scipy import stats

bb=pd.read_csv("Earthquakes_new.csv",sep=";")
earthquakes_new_2=np.array(bb)
earthquakes_new_2

array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 4.100e+00, 7.000e+00,
        0.000e+00],
       [2.000e+00, 0.000e+00, 0.000e+00, ..., 4.400e+00, 7.000e+00,
        0.000e+00],
       [3.000e+00, 0.000e+00, 0.000e+00, ..., 4.000e+00, 7.000e+00,
        0.000e+00],
       ...,
       [6.571e+03, 4.000e+00, 0.000e+00, ..., 4.800e+00, 2.000e+00,
        0.000e+00],
       [6.572e+03, 3.000e+00, 0.000e+00, ..., 5.200e+00, 2.000e+00,
        0.000e+00],
       [6.573e+03, 2.000e+00, 0.000e+00, ..., 4.400e+00, 2.000e+00,
        0.000e+00]])

In [2]:
print(np.mean(earthquakes_new_2, axis = 0))
print("\n")
print(np.std(earthquakes_new_2, axis = 0))

[3.28700000e+03 5.50033866e+03 0.00000000e+00 8.86961813e-02
 0.00000000e+00 1.81473635e+02 1.56940270e+02 2.49842462e+01
 0.00000000e+00 1.01455956e+01 0.00000000e+00 0.00000000e+00
 4.46767077e+00 6.77650997e+00 0.00000000e+00]


[1.89746164e+03 3.97624224e+03 0.00000000e+00 4.06715671e-01
 0.00000000e+00 1.69615858e+02 1.53319049e+02 2.77585355e+01
 0.00000000e+00 1.27987480e+01 0.00000000e+00 0.00000000e+00
 4.85684311e-01 5.41201695e+00 0.00000000e+00]


In [3]:
earthquakes_new_2.shape

(6573, 15)

In [4]:
earthquakes_new_2 = np.delete(earthquakes_new_2, (1, 25, 25, 10, 4), axis=0)
earthquakes_new_2.shape

(6569, 15)

In [6]:
earthquakes_new_3 = earthquakes_new_2 * 2
print(earthquakes_new_3)

[[2.0000e+00 0.0000e+00 0.0000e+00 ... 8.2000e+00 1.4000e+01 0.0000e+00]
 [6.0000e+00 0.0000e+00 0.0000e+00 ... 8.0000e+00 1.4000e+01 0.0000e+00]
 [8.0000e+00 0.0000e+00 0.0000e+00 ... 9.0000e+00 1.4000e+01 0.0000e+00]
 ...
 [1.3142e+04 8.0000e+00 0.0000e+00 ... 9.6000e+00 4.0000e+00 0.0000e+00]
 [1.3144e+04 6.0000e+00 0.0000e+00 ... 1.0400e+01 4.0000e+00 0.0000e+00]
 [1.3146e+04 4.0000e+00 0.0000e+00 ... 8.8000e+00 4.0000e+00 0.0000e+00]]
